### ISSUE TITLE
Add more commands?

### ISSUE THREAD

**Issue by ionut-tanasa** [prettus/l5-repository#53]
Adding more commands

- [x] make:transformer (merged #55)
- [x] make:presenter (merged #57)
- [x] make:entity - (merged #58)

the make:entity command would generate the Repository, the Transformer, the Presenter and the Validator for that entity.

**Comment by Jeroen-G** [comment]
I see the value in this as well, although the `make:validator` should go in the validator package. I could contribute too.

**Comment by ionut-tanasa** [comment]
Yea sure, the command for validator should go into the validator package.

**Comment by Jeroen-G** [comment]
I think you should just place a PR. Although I don't know if @andersao prefers it on the master or develop branch.

**Comment by hiddeco** [comment]
+1.

@ionut-tanasa @Jeroen-G 
From what I know. PR quick fixes and small additions to master, completely new functions to develop.
So master would be more suitable for this.

**Comment by andersao** [comment]
Hello guys @ionut-tanasa @Jeroen-G @hiddeco ,

I liked the suggestion and I think it will be great to add new commands . What about the branch , the @hiddeco  is right. Rather than new features being sent to branch Develop or create other specific branch .

The contribution of you will be very well accepted ;)

**Comment by hiddeco** [comment]
@ionut-tanasa, are you gonna make a PR? Otherwise I will make one this week. 






On Monday 29 Jun 2015 at 16:42, Anderson Andrade <notifications@github.com>, wrote:

Hello guys @ionut-tanasa @Jeroen-G @hiddeco ,


I liked the suggestion and I think it will be great to add new commands . What about the branch , the @hiddeco  is right. Rather than new features being sent to branch Develop or create other specific branch .


The contribution of you will be very well accepted ;)

**Comment by ionut-tanasa** [comment]
@hiddeco please do.

I just started the command for the transformer. Maybe you can do the other one/ones?

**Comment by Jeroen-G** [comment]
If you've created a PR-repo you can give others push access to it, so it can be one PR.

**Comment by ionut-tanasa** [comment]
Check #55.

I gave you push access to the repo.

Now it's basic stuff. Maybe we could specify with which properties the return array from the transformer will be filled. Like the --fillable argument for the Model

**Comment by hiddeco** [comment]
That is actually a great idea, you just want to copy the column names from the database to the transformer than? Because most transformers contain different names than the database columns do (at least mine do).

**Comment by ionut-tanasa** [comment]
@andersao I love that you are merging so quick my PRs

I'll make the basic presenter command and pr it. then you could improve it and more features to it

**Comment by andersao** [comment]
And I 'm loving the contribution of you.

**Comment by ionut-tanasa** [comment]
Just a quick question. I'm trying to understand how to pass variables to the stubs.

In the presenter, obviously, I need to use the transformer class. How do I get the root namespace and pass it to the stub in order to write the exact namespace of the transformer?

I am assuming that the Presenter will use a Transformer with the same name.

So when I run make:presenter MODEL, I assume that you already have a MODELTRansformer created.
Maybe I can check that, if the transformer does not exist I can create it for the user.

So how do I pass the root namespace, i.e. App so on top of the class I can use App\Transformers\MODELTransformer ?

**Comment by hiddeco** [comment]
Laravel has a trait for this: `Illuminate\Console\AppNamespaceDetectorTrait`

Then you could use `$this->getAppNamespace()`

**Comment by ionut-tanasa** [comment]
Maybe I didn't explain myself very well :smile: 

I know how to get the app namespace from Laravel. My question was: How do I pass the namespace as $APPNAMESPACE$ to the stub file?

**Comment by hiddeco** [comment]
If you take a quick look at the [ModelGenerator.php](https://github.com/prettus/l5-repository/blob/master/src/Prettus/Repository/Generators/ModelGenerator.php) you can find the getReplacement() function. This loads the replacements for the stub file.

Quick untested example

````php
    /**
     * Get array replacements.
     *
     * @return array
     */
    public function getReplacements()
    {
        return array_merge(parent::getReplacements(), [
            'appnamespace' => $this->getAppNamespace()
        ]);
    }
````

**Comment by ionut-tanasa** [comment]
thank you @hiddeco 

@andersao PR done #57

**Comment by ionut-tanasa** [comment]
Done. Closing
